apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "dunasaks"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "dunasaks"
    spec:
      containers:
        - name: "dunasaks"
          image: "dunasacr.azurecr.io/dunasaks"
          ports:
          - containerPort: 8080