on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dunasacr.azurecr.io
        username: ${{ secrets.acr_dunasacr_username }}
        password: ${{ secrets.acr_dunasacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t dunasacr.azurecr.io/dunasaks:${{ github.sha }}
        docker push dunasacr.azurecr.io/dunasaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_dunasaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dunasaks85ea | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dunasaks85ea`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dunasaks85ea
        container-registry-url: dunasacr.azurecr.io
        container-registry-username: ${{ secrets.acr_dunasacr_username }}
        container-registry-password: ${{ secrets.acr_dunasacr_password }}
        secret-name: dunasaksdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: dunasaks85ea
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          dunasacr.azurecr.io/dunasaks:${{ github.sha }}
        imagepullsecrets: |
          dunasaksdockerauth